### ISSUE TITLE
Boost error on master branch

### ISSUE THREAD

**Issue by vuphan314** [shawn-peng/counting-consistent-sub-DAG#2]
@shawn-peng @yuxjiang 
I can run `make` on the `newboost` branch. But `make` shows an error on the `master` branch:
```
cc -c -o random_device.o random_device.cpp -g -std=c++0x -lstdc++ -lgmpxx -lgmp
random_device.cpp:20:41: error: ‘const result_type boost::random::random_device::min_value’ is not a static data member of ‘class boost::random::random_device’
   20 | const boost::random_device::result_type boost::random_device::min_value;
```
Do you know how to fix that? Thank you.

**Comment by shawn-peng** [comment]
Hi, @vuphan314. First, I must apologize. I had a lot of commits that were pushed to my previous school git and weren't synced here. I just synced them. If I remember correctly, the major change is I added the pivoting branch, which allows you to provide a partial order of nodes that you want the algorithm to remove when enumerating.

I think the reason you got this error is that you have a new version of Boost on your machine. That's what the newboost branch aimed for. The master branch is targeting machines with old Boost libraries.

To solve this issue, I suggest you change the Makefile as in newboost branch.
```make
#CPPFLAGS+=-O3 -lstdc++
ifeq ($(strip $(OPT)),)
	#default value
	OPT=-g
endif

CPPFLAGS+=$(OPT) -std=c++0x -lstdc++ -lgmpxx -lgmp -lboost_random -lm

all: graph_alg graph_gen analyze_graph batch_graph_gen estimate_bound same_graph_gen

graph_alg: main.o graph_alg.o dag_generator.o dag.o
	$(CC) -o $@ $^ $(CPPFLAGS)

graph_gen: graph_gen.o dag_generator.o dag.o
	$(CC) -o $@ $^ $(CPPFLAGS)

batch_graph_gen: batch_graph_gen.o dag_generator.o dag.o graph_alg.cpp
	$(CC) -o $@ $^ $(CPPFLAGS)

analyze_graph: analyze_graph.o dag_generator.o dag.o
	$(CC) -o $@ $^ $(CPPFLAGS)

estimate_bound: estimate_bound.o graph_alg.o dag_generator.o dag.o
	$(CC) -o $@ $^ $(CPPFLAGS)

same_graph_gen: same_graph_gen.o dag_generator.o dag.o graph_alg.cpp
	$(CC) -o $@ $^ $(CPPFLAGS)

%.o: %.cpp
	$(CC) -c -o $@ $^ $(CPPFLAGS)

clean:
	rm -f *.o graph_alg
```
It just removes the random_device.cpp from the objects and links to boost_random library.

I think we can assume this is pretty common now and apply this change to the master branch while create an oldboost branch. What do you think?

Please don't hesitate to reach out if you have any questions about the algorithm. I didn't leave many comments in the code. You can contact me at peng.yis@northeastern.edu

**Comment by vuphan314** [comment]
Thank you. As you suggested, I can now run `make` on the `master` branch using the `Makefile` from the `newboost` branch. My Boost version is 1.74.

I agree that the default branch should support a new version of Boost. There are 2 choices:

1. As you wrote, create an `oldboost` branch from `master` before merging `newboost` into `master`.
2. Alternatively, simply make `newboost` the default branch ([instruction](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch)), without a branch creation or merge.

It is your choice.

Either way, my issue is now resolved. I am closing it. Thanks again.
